- name: "Provision User Play"
  strategy: linear
  hosts: all
  become: true
  vars_files:
    - vars/vars.yml
    - vars/vault.yml
  tasks:

  - name: Setup User
    when: provision_user == true
    include: tasks/user_provisioning.yml